import './globals.css'
import { Rubik } from 'next/font/google';
import GlobalProvider from '@/context/GlobalContext';

const fonts = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <GlobalProvider>
          {children}
        </GlobalProvider>
        </body>
    </html>
  )
}
